apiVersion: v1
kind: Secret
metadata:
  name: payment-secrets
  namespace: hms
type: Opaque
stringData:
  DSN: "postgres://user:pass123@postgres:5432/payment?sslmode=disable"   # Use service name in K8s
  JWT_SECRET: "your-super-secret-jwt-key-32-chars-minimum-here"