apiVersion: v1
kind: Service
metadata:
  labels:
    app: patient
  name: patient
spec:
  ports:
  - name: http
    port: 4001
    protocol: TCP
    targetPort: 4001
  selector:
    app: hms-patient
  type: ClusterIP

