apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: hms
type: Opaque
stringData:
  DSN: "postgres://user:pass123@postgres:5432/auth?sslmode=disable"   
  JWT_SECRET: "your-super-secret-jwt-key-32-chars-minimum-here"
  