apiVersion: v1
kind: Service
metadata:
  labels:
    app: hms-lab
  name: hms-lab
spec:
  ports:
  - name: http
    port: 4003
    protocol: TCP
    targetPort: 4003
  selector:
    app: hms-lab
  type: ClusterIP

