apiVersion: v1
kind: Service
metadata:
  labels:
    app: pharmacy
  name: pharmacy
spec:
  ports:
  - name: http
    port: 4004
    protocol: TCP
    targetPort: 4004
  selector:
    app: pharmacy
  type: ClusterIP
